# Generated by Django 4.1.7 on 2023-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteriaDesc', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteriaLevel', models.CharField(choices=[(0, 'Level 1'), (1, 'Level 2'), (2, 'Level 3'), (3, 'Level 4')], default='0', max_length=100)),
            ],
        ),
    ]
