# Generated by Django 4.1.7 on 2023-03-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markingApp', '0002_criteria_criterialevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='criteriaDesc',
            new_name='criteriaDescription',
        ),
    ]
