# Generated by Django 4.1.7 on 2023-03-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markingApp', '0003_rename_criteriadesc_criteria_criteriadescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterialevel',
            name='criteriaLevelDescription',
            field=models.CharField(default='placeholder', max_length=1000000),
            preserve_default=False,
        ),
    ]
