# Generated by Django 4.1.7 on 2023-03-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markingApp', '0004_criterialevel_criterialeveldescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='assignmentID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='markingApp.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterialevel',
            name='criteriaID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='markingApp.criteria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criterialevel',
            name='criteriaLevelDescription',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentFirstName', models.CharField(max_length=100)),
                ('studentLastName', models.CharField(max_length=100)),
                ('mark', models.IntegerField()),
                ('submissionFile', models.CharField(max_length=1000)),
                ('assignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markingApp.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('criteriaLevelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markingApp.criterialevel')),
                ('submissionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markingApp.submission')),
            ],
        ),
    ]
