# Generated by Django 4.1.7 on 2023-03-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markingApp', '0005_criteria_assignmentid_criterialevel_criteriaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='criteriaDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submissionFile',
            field=models.FileField(upload_to=''),
        ),
    ]
