# Generated by Django 4.1.7 on 2023-03-26 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markingApp', '0006_alter_criteria_criteriadescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submissionFile',
            field=models.FileField(upload_to='submissions', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
