# Generated by Django 4.1.7 on 2023-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markingApp', '0007_alter_submission_submissionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
