# Generated by Django 4.1.7 on 2023-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markingApp', '0011_criteria_criteriatotalmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='criteriaTotalMark',
            field=models.IntegerField(default=0),
        ),
    ]
