# Generated by Django 4.1.7 on 2023-04-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markingApp', '0012_alter_criteria_criteriatotalmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterialevel',
            name='criteriaLevel',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], null=True),
        ),
    ]
