# Generated by Django 4.1.7 on 2023-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markingApp', '0013_alter_criterialevel_criterialevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='criteriaTotalMark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criterialevel',
            name='criteriaLevel',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], default=0),
        ),
    ]
