# Generated by Django 4.1.7 on 2023-05-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markingApp', '0016_alter_submission_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
